// <auto-generated />
using System;
using AnkiBridge.Domain.Aggregates.Learning;
using AnkiBridge.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnkiBridge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryEntryId");

                    b.ToTable("DictionaryDefinition", "Dictionary");
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Headword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Headword", "PartOfSpeech");

                    b.ToTable("DictionaryEntry", "Dictionary");
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.ToTable("DictionaryExample", "Dictionary");
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryEntryId");

                    b.ToTable("DictionaryImage", "Dictionary");
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryPronunciation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accent")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("AudioSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ipa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryEntryId");

                    b.ToTable("DictionaryPronunciation", "Dictionary");
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryEntryId");

                    b.ToTable("DictionaryTranslation", "Dictionary");
                });

            modelBuilder.Entity<LearningEntry>(b =>
                {
                    b.Property(entry => entry.Id)
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property(entry => entry.Accent)
                        .IsRequired()
                        .HasConversion<string>()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property(entry => entry.AudioDownloadStatus)
                        .HasConversion<string>()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property(entry => entry.AudioPath)
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property(entry => entry.AudioSource)
                        .HasConversion<string>()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property(entry => entry.Cloze)
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property(entry => entry.CreatedAt)
                        .HasColumnType("timestamp with time zone");

                    b.Property(entry => entry.Definition)
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property(entry => entry.DeletedAt)
                        .HasColumnType("timestamp with time zone");

                    b.Property(entry => entry.DeletedBy)
                        .HasColumnType("uuid");

                    b.Property(entry => entry.DictionaryEntryId)
                        .HasColumnType("uuid");

                    b.Property(entry => entry.Headword)
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property(entry => entry.ImageDownloadStatus)
                        .HasConversion<string>()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property(entry => entry.ImagePath)
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property(entry => entry.ImageSource)
                        .HasConversion<string>()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property(entry => entry.Ipa)
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property(entry => entry.IsDeleted)
                        .HasColumnType("boolean");

                    b.Property(entry => entry.PartOfSpeech)
                        .IsRequired()
                        .HasConversion<string>()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property(entry => entry.Translation)
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property(entry => entry.TranslationSource)
                        .IsRequired()
                        .HasConversion<string>()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey(entry => entry.Id);

                    b.HasIndex(entry => entry.CreatedAt);
                    b.HasIndex(entry => entry.DictionaryEntryId);

                    b.ToTable("LearningEntry", "Learning");
                    b.HasQueryFilter(entry => !entry.IsDeleted);
                });

            modelBuilder.Entity<LearningExample>(b =>
                {
                    b.Property(example => example.Id)
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LearningEntryId")
                        .HasColumnType("uuid");

                    b.Property(example => example.OrderIndex)
                        .HasColumnType("integer");

                    b.Property(example => example.Text)
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey(example => example.Id);
                    b.HasIndex("LearningEntryId");

                    b.ToTable("LearningExample", "Learning");
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryDefinition", b =>
                {
                    b.HasOne("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryEntry", null)
                        .WithMany("Definitions")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryExample", b =>
                {
                    b.HasOne("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryDefinition", null)
                        .WithMany("Examples")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryImage", b =>
                {
                    b.HasOne("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryEntry", null)
                        .WithMany("Images")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryPronunciation", b =>
                {
                    b.HasOne("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryEntry", null)
                        .WithMany("Pronunciations")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryTranslation", b =>
                {
                    b.HasOne("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryEntry", null)
                        .WithMany("Translations")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity<LearningExample>(b =>
                {
                    b.HasOne<LearningEntry>()
                        .WithMany(entry => entry.Examples)
                        .HasForeignKey("LearningEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryDefinition", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("AnkiBridge.Domain.Aggregates.Dictionary.DictionaryEntry", b =>
                {
                    b.Navigation("Definitions");

                    b.Navigation("Images");

                    b.Navigation("Pronunciations");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity<LearningEntry>(b =>
                {
                    b.Navigation(entry => entry.Examples);
                });
#pragma warning restore 612, 618
        }
    }
}
